[package]
name = "to_mysql"
version = "0.1.7"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/rust.git"
homepage = "https://github.com/js0-site/rust/tree/main/to_mysql"
description = "Efficient MySQL SQL Generation / 高效 MySQL SQL 生成"
keywords = ["mysql", "sql", "generation", "struct", "orm"]
categories = ["database", "development-tools", "parsing", "algorithms", "data-structures"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dependencies.sqle]
version = "0.1.4"
path = "../sqle"
features = ["mysql"]

[dependencies.vb]
version = "0.2.7"
path = "../vb"

[dependencies.kind2sql]
path = "../kind2sql"
version = "0.1.18"
features = ["sql_field"]

[dev-dependencies]
aok = "0.1.18"
linkme = "0.3.37"
log = "0.4.34"
log_init = "0.1.39"

[dev-dependencies.static_init]
version = "1.0.4"
features = ["parking_lot"]

[dev-dependencies.tosql]
path = "../tosql"
version = "0.1.16"

[dev-dependencies.tokio]
version = "1.53.1"
features = ["macros", "rt", "rt-multi-thread", "time", "sync"]
