[package]
name = "ver_from_txt"
version = "0.1.12"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/rust.git"
homepage = "https://github.com/js0-site/rust/tree/dev/ver_from_txt"
description = "Parse version info from DNS TXT / 从 DNS TXT 解析版本信息"
keywords = ["dns", "version", "update", "txt", "parser"]
categories = [
  "network-programming",
  "parsing",
  "development-tools",
  "algorithms",
  "data-structures",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dependencies]
base64 = "0.23.1"
log = "0.4.34"
thiserror = "2.0.20"

[dependencies.vb]
version = "0.2.7"

[dependencies.sver]
version = "0.1.10"

[dev-dependencies]
aok = "0.1.18"
log_init = { version = "0.1.39" }
static_init = { version = "1.0.4", features = ["parking_lot"] }
