[package]
name = "idoh"
version = "0.1.15"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/rust.git"
homepage = "https://github.com/js0-site/rust/tree/dev/idoh"
description = "Fast and secure DNS over HTTPS resolution / 极速安全的 DoH 解析库"
keywords = [ "dns", "doh", "https", "async", "resolver" ]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [ "--cfg", "docsrs" ]

[features]
default = [ ]
mx = [ ]
cache = [ "dep:expire_cache", "dep:dashmap", "dep:static_init" ]

[dependencies]
defer-lite = "1.0.0"
sonic-rs = "0.5.6"
crossfire = "2.1.8"
log = "0.4.29"
thiserror = "2.0.17"

[dependencies.ireq]
version = "0.1.32"
path = "../ireq"
features = [ "proxy" ]

[dependencies.expire_cache]
version = "0.1.15"
path = "../expire_cache"
features = [ "dashmap", "get_or_init_async" ]
optional = true

[dependencies.dashmap]
version = "6.1.0"
optional = true

[dependencies.static_init]
version = "1.0.4"
optional = true

[dependencies.riter]
version = "0.1.1"

[dependencies.serde]
version = "1.0.228"
features = [ "derive" ]

[dependencies.tokio]
version = "1.48.0"
features = [ "time", "net", "rt" ]

[dependencies.xerr]
version = "0.1.16"

[dev-dependencies]
aok = "0.1.18"
log_init = "0.1.28"
static_init = "1.0.4"

[dev-dependencies.tokio]
version = "1.48.0"
features = [ "test-util", "macros" ]
