[package]
name = "tosql"
version = "0.1.16"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/rust.git"
homepage = "https://github.com/js0-site/rust/tree/main/tosql"
description = "Trait for SQL struct serialization / SQL结构体序列化Trait"
keywords = ["sql", "trait", "serialization", "database", "struct"]
categories = ["database", "development-tools", "parsing", "algorithms", "data-structures"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dependencies]
bytes = "1.11.1"
linkme = "0.3.36"

[dependencies.tosql_macro]
version = "0.1.1"
path = "../tosql_macro"

[dependencies.tosql_linkme]
version = "0.2.4"
path = "../tosql_linkme"

[dependencies.tosql_static_meta]
version = "0.1.4"
path = "../tosql_static_meta"

[dependencies.vb]
version = "0.2.7"
path = "../vb"

[dependencies.kind2sql]
version = "0.1.18"
path = "../kind2sql"
features = ["sql_field"]

[dependencies.tosql_derive]
version = "0.1.14"
path = "../tosql_derive"

[dev-dependencies]
aok = "0.1.18"
log = "0.4.30"
log_init = "0.1.34"

[dev-dependencies.static_init]
version = "1.0.4"
features = ["parking_lot"]

[dev-dependencies.tokio]
version = "1.52.3"
features = ["macros", "rt", "rt-multi-thread", "time", "sync"]
