[package]
authors = ["jssite@googlegroups.com", "ayazhafiz <ayaz.hafiz.1@gmail.com>"]
categories = ["algorithms", "data-structures", "compression", "database", "caching-implementations"]
description = """
Library implementing xor filters - faster and smaller than bloom and cuckoo filters.
"""
edition = "2024"
homepage = "https://github.com/js0-site/rust/tree/main/jdb_xorf"
keywords = ["xor", "filter", "hash", "hashing"]
license = "MIT"
name = "jdb_xorf"
readme = "README.md"
repository = "https://github.com/js0-site/rust"
version = "0.12.2"

[badges.is-it-maintained-issue-resolution]
repository = "ayazhafiz/xorf"

[badges.is-it-maintained-open-issues]
repository = "ayazhafiz/xorf"

[badges.maintenance]
status = "actively-developed"

[badges.travis-ci]
branch = "master"
repository = "ayazhafiz/xorf"

[dependencies]
libm = { version = "0.2.15", optional = true }
bitcode = { version = "0.6", optional = true }
fastrand = { version = "2", optional = true }

[dev-dependencies]
criterion = "0.8.1"
criterion-macro = "0.4.0"
rand = "0.9"

[[bench]]
name = "bfuse32"
harness = false

[[bench]]
name = "bfuse16"
harness = false

[[bench]]
name = "bfuse8"
harness = false
required-features = ["bitcode"]

[[bench]]
name = "xor32"
harness = false

[[bench]]
name = "xor16"
harness = false

[[bench]]
name = "xor8"
harness = false

[features]
default = ["uniform-random", "binary-fuse"]
uniform-random = ["fastrand"]
binary-fuse = ["libm"]
bitcode = ["dep:bitcode"]