[package]
name = "xboot"
version = "0.1.33"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/rust.git"
homepage = "https://github.com/js0-site/rust/tree/main/xboot"
description = "Async static initialization before main. / 主函数前异步初始化静态变量。"
keywords = ["async", "static", "initialization", "linkme", "tokio"]

[features]
default = []

[package.metadata.docs.rs]
all-features = true

[dependencies]
aok = "0.1.18"
gensym = "0.1.1"
linkme = "0.3.35"
paste = "1.0.15"
tokio = { version = "1.48.0", features = ["rt"] }