[package]
name = "compio_dns_test"
version = "0.1.0"
edition = "2024"

[dependencies]
compio-net = "0.11.0"
compio_dns = { path = "..", optional = true }
compio = { version = "0.18.0", features = ["macros"] }
aok = "0.1.18"
sonic-rs = "0.5.6"
serde = { version = "1.0.228", features = ["derive"] }
fastrand = "2.3.0"

[features]
default = ["dep:compio_dns"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(compio_dns)'] }
