[package]
name = "sqle"
version = "0.1.4"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/rust.git"
homepage = "https://github.com/js0-site/rust/tree/main/sqle"
description = "Concise SQL string escaping and formatting / 简洁的 SQL 字符串转义与格式化"
keywords = ["sql", "escape", "format", "mysql", "postgres"]
categories = ["database", "development-tools", "parsing", "text-processing", "algorithms"]

[features]
default = []
mysql = ["dep:faster-hex"]
postgres = ["dep:faster-hex"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
faster-hex = { version = "0.10.0", optional = true }

[dev-dependencies]
aok = "0.1.18"
log = "0.4.33"
log_init = "0.1.38"
static_init = { version = "1.0.4", features = ["parking_lot"] }

[dev-dependencies.tokio]
version = "1.52.3"
features = ["macros", "rt", "rt-multi-thread", "time", "sync"]
