/// Fixed-point: Key = (index * slope_fp + intercept_fp) >> 32
/// 定点数：Key = (index * slope_fp + intercept_fp) >> 32
#[derive(Clone, Copy, Debug, Default)]
#[repr(C)]
pub struct CompactSegment {
  pub start_idx: u32,
  pub slope_fp: u64,
  pub intercept_fp: i64,
}

/// BlockMeta.seg_idx flag: block has exceptions
/// BlockMeta.seg_idx 标志位：块有异常值
pub const FLAG_HAS_EX: u32 = 0x8000_0000;

/// BlockMeta.seg_idx flag: block contains single segment (no segment crossing)
/// BlockMeta.seg_idx 标志位：块只包含单一段（无跨段）
pub const FLAG_SINGLE_SEG: u32 = 0x4000_0000;

/// BlockMeta.seg_idx mask: extract segment index (lower 30 bits)
/// BlockMeta.seg_idx 掩码：提取段索引（低 30 位）
pub const MASK_SEG_IDX: u32 = 0x3FFF_FFFF;

#[derive(Clone, Copy, Debug, Default)]
#[repr(C)]
pub struct BlockMeta {
  /// Bit offset in the residuals array
  /// 残差数组中的位偏移
  pub bit_offset: u32,
  /// Bit width for each element in the block
  /// 块中每个元素的位宽
  pub bit_width: u8,
  /// Index of the first segment covering this block (with flags in high bits)
  /// 覆盖该块起始位置的段索引（高位含标志位）
  pub seg_idx: u32,
  /// Start index in the exceptions array for this block
  /// 该块在异常值数组中的起始索引
  pub exception_offset: u32,
}

/// Exception penalty multiplier for PFOR cost calculation.
/// PFOR 代价计算中的离群值惩罚系数。
///
/// Controls the trade-off between compression ratio and query speed:
/// 控制压缩率和查询速度之间的权衡：
///
/// - Value range: 1-16 (inclusive)
/// - 取值范围：1-16（含）
///
/// - `1`: Minimize space (more exceptions allowed, slower queries)
/// - `1`：最小化空间（允许更多离群值，查询较慢）
///
/// - `4-8`: Balanced (recommended for most use cases)
/// - `4-8`：平衡（推荐用于大多数场景）
///
/// - `16`: Minimize exceptions (fewer exceptions, faster queries, larger space)
/// - `16`：最小化离群值（更少离群值，查询更快，占用更多空间）
#[derive(Clone, Copy, Debug)]
pub struct ExPenalty(u8);

impl ExPenalty {
  /// Minimum allowed value
  /// 允许的最小值
  pub const MIN: u8 = 1;

  /// Maximum allowed value
  /// 允许的最大值
  pub const MAX: u8 = 16;

  /// Create a new ExPenalty with range validation.
  /// 创建新的 ExPenalty，带范围验证。
  ///
  /// # Panics
  /// Panics if `val` is not in range [1, 16].
  /// 如果 `val` 不在 [1, 16] 范围内则 panic。
  #[inline]
  pub fn new(val: u8) -> Self {
    assert!(
      (Self::MIN..=Self::MAX).contains(&val),
      "ExPenalty must be in range [{}, {}], got {}",
      Self::MIN,
      Self::MAX,
      val
    );
    Self(val)
  }

  /// Get the inner value.
  /// 获取内部值。
  #[inline]
  pub fn get(self) -> u8 {
    self.0
  }
}

impl Default for ExPenalty {
  /// Default is generated by build.rs.
  /// 默认值由 build.rs 生成。
  fn default() -> Self {
    Self(DEFAULT_EX_PENALTY)
  }
}

/// Configuration for Pc (Compressed PGM) index.
/// Pc（压缩 PGM）索引的配置。
#[derive(Clone, Copy, Debug)]
pub struct PcConf {
  /// PGM epsilon (prediction error tolerance).
  /// PGM epsilon（预测误差容忍度）。
  pub epsilon: usize,

  /// Exception penalty multiplier.
  /// 离群值惩罚系数。
  pub ex_penalty: ExPenalty,
}

impl PcConf {
  /// Create a new configuration.
  /// 创建新配置。
  #[inline]
  pub fn new(epsilon: usize, ex_penalty: ExPenalty) -> Self {
    Self {
      epsilon,
      ex_penalty,
    }
  }

  /// Create configuration with default ex_penalty (1).
  /// 使用默认离群值惩罚（1）创建配置。
  #[inline]
  pub fn with_epsilon(epsilon: usize) -> Self {
    Self {
      epsilon,
      ex_penalty: ExPenalty::default(),
    }
  }
}

impl Default for PcConf {
  fn default() -> Self {
    Self {
      epsilon: DEFAULT_EPSILON,
      ex_penalty: ExPenalty::default(),
    }
  }
}

include!(concat!(env!("OUT_DIR"), "/pc_consts.rs"));
