[package]
name = "ssl_trait"
version = "0.1.3"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/rust.git"
homepage = "https://github.com/js0-site/rust/tree/main/ssl_trait"
description = "ssl_trait"
keywords = []
categories = ["cryptography", "network-programming", "development-tools", "asynchronous", "api-bindings"]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
anyhow = "1.0.101"
rustls = "0.23.36"

[dev-dependencies]
aok = "0.1.18"
log = "0.4.29"
log_init = "0.1.34"
static_init = { version = "1.0.4", features = ["parking_lot"] }

[dev-dependencies.tokio]
version = "1.49.0"
features = ["macros", "rt", "rt-multi-thread", "time", "sync"]
