[package]
name = "idoq"
version = "0.1.10"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-dns/rust.git"
homepage = "https://github.com/js0-dns/rust/tree/main/idoq"
description = "DNS over QUIC (DoQ) client / DNS over QUIC (DoQ) 客户端"
keywords = [ "dns", "quic", "doq", "resolver" ]
categories = ["network-programming", "asynchronous", "cryptography", "api-bindings", "development-tools"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [ "--cfg", "docsrs" ]

[features]
default = [ "static" ]
static = [ "dep:static_init" ]

[dependencies]
bytes = "1.11.0"
futures = "0.3.31"
log = "0.4.29"
quinn = "0.11.9"
hipstr = "0.8"
thiserror = "2.0.17"
webpki-roots = "1.0.5"

[dependencies.dns_parse]
version = "0.1.2"
path = "../dns_parse"

[dependencies.static_init]
version = "1.0.4"
optional = true
features = [ "parking_lot" ]

[dependencies.idns]
version = "0.2.13"
path = "../idns"

[dependencies.rustls]
version = "0.23.36"
features = [ "ring" ]

[dependencies.tokio]
version = "1.49.0"
features = [ "io-util", "net" ]

[dev-dependencies]
aok = "0.1.18"
futures = "0.3.31"
log = "0.4.29"
log_init = "0.1.34"
tabled = "0.20.0"

[dev-dependencies.static_init]
version = "1.0.4"
features = [ "parking_lot" ]

[dev-dependencies.idns]
version = "0.2.13"
path = "../idns"
features = [ "mx", "cache" ]

[dev-dependencies.tokio]
version = "1.49.0"
features = [ "macros", "rt", "rt-multi-thread", "time", "sync" ]
