[package]
name = "kv2db"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/rust.git"
homepage = "https://github.com/js0-site/rust/tree/main/kv2db"
description = "kv2db"
keywords = [ ]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [ "--cfg", "docsrs" ]

[features]
default = [ ]

[dev-dependencies]
aok = "0.1.18"
log = "0.4.28"
log_init = "0.1.28"
static_init = "1.0.4"

[dev-dependencies.tokio]
version = "1.48.0"
features = [ "macros", "rt", "rt-multi-thread", "time", "sync" ]
