[package]
name = "tosql_macro"
version = "0.1.1"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/rust.git"
homepage = "https://github.com/js0-site/rust/tree/main/tosql_macro"
description = "tosql_macro"
keywords = []
categories = [
  "development-tools::procedural-macro-helpers",
  "development-tools",
  "parsing",
  "database",
  "algorithms",
]

[lib]
proc-macro = true

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
aok = "0.1.18"
log = "0.4.33"
log_init = "0.1.38"
static_init = { version = "1.0.4", features = ["parking_lot"] }

[dev-dependencies.tokio]
version = "1.52.3"
features = ["macros", "rt", "rt-multi-thread", "time", "sync"]
