[package]
name = "jdb_lru"
version = "0.1.8"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/rust.git"
homepage = "https://github.com/js0-site/rust/tree/main/jdb_lru"
description = "Efficient LRU cache with zero-allocation alternatives / 高效LRU缓存与零分配替代方案"
keywords = ["lru", "cache", "memory", "performance", "rust"]
categories = ["algorithms", "data-structures", "database"]
readme = "README.md"

[features]
default = ["lru", "no"]
lru = ["dep:hashlink"]
no = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
hashlink = { version = "0.12.1", optional = true }

[dev-dependencies]
aok = "0.1.18"
compio = { version = "0.19.2", features = ["macros"] }
log = "0.4.34"
log_init = "0.1.39"
static_init = "1.0.4"
