[package]
name = "tosql_derive"
version = "0.1.14"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/js0-site/rust.git"
homepage = "https://github.com/js0-site/rust/tree/main/tosql_derive"
description = "Derive macro for ToSqlTrait trait / ToSqlTrait trait 派生宏"
keywords = [ "sql", "macro", "derive", "serialization", "codegen" ]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [ "--cfg", "docsrs" ]

[lib]
proc-macro = true

[features]
default = [ ]

[dependencies]
quote = "1"
proc-macro2 = "1"
bytes = "1.11.0"

[dependencies.syn]
version = "2"
features = [ "full", "extra-traits" ]

[dependencies.vb]
version = "0.2.5"
path = "../vb"

[dev-dependencies]
aok = "0.1.18"
log = "0.4.28"
log_init = "0.1.28"
static_init = "1.0.4"
bytes = "1.11.0"